name: easy_date_timeline
description: The "easy_date_timeline" package is a customizable Flutter library that displays a timeline of dates in a horizontal view.
version: 2.0.5
homepage: https://github.com/FadyFayezYounan/easy_date_timeline.git

topics:
  - calendar
  - picker
  - widgets
  - timeline
  - date-time

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  generate: true
